site_name: Entrepreneurship in Norway
site_url: https://onyku.com/pre-onyku-provider-entrepreneurship-in-norway
nav:
  - Home: index.md
  - Lessons learned:
    - Keep salary low initially: lessons-learned/keep-salary-low-initially
theme: readthedocs
plugins:
  - search
  - mermaid2