site_name: Entrepreneurship in Norway
repo_url: https://github.com/CalvetIT/pre-onyku-provider-entrepreneurship-in-norway
edit_uri: edit/main/docs/
nav:
  - Onyku website: https://onyku.com
  - Home: index.md
  - Lessons learned:
    - Keep salary low initially: lessons-learned/keep-salary-low-initially
theme: readthedocs
plugins:
  - search
  - mermaid2